name: linter-github-action
on: push
  jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
        - run : apt install python3-pip
        - run: python -m pip install flake8
        - run: flake8 .